sudo: false
language: java
install: true

addons:
  sonarcloud:
    organization: "buchen-github"
    token:
      secure: "dt+zJiG0qtD/4Fkka+HjxyFiOzccObpopgQXCf73X7OIk9pqwzFurkYBVUf2G8NuK5q9fib5R101wREFf0TSa8pF3dWBMGIC8iwNNrbuODXpMqxzjaZcpog62C+dPxJOtK4W6OGCLUWf+Lg5gtNWDnckW7IRiM6G0N4a9Fhn2ic="

script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn -f ./portfolio-app/pom.xml verify
  -Dtycho.disableP2Mirrors; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn -f ./portfolio-app/pom.xml verify
  sonar:sonar -Dtycho.disableP2Mirrors; fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
- oraclejdk8
