name: Build and Release with TLVTrade

on:
  workflow_call: # This allows the sync workflow to "call" this one
  push:
    branches: TLVTrade2

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-mvn
        restore-keys: |
          ${{ runner.os }}-mvn-
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: zulu
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11
    - name: Build with Maven
      run: |
        mvn verify \
        --batch-mode \
        --file portfolio-app/pom.xml

    -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        --file portfolio-app/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
