name: CI

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Maven Build
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        mvn verify \
        --batch-mode \
        --file portfolio-app/pom.xml

  build-analyze:
    name: Maven Build + Sonar Analysis
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        mvn verify sonar:sonar \
        --batch-mode \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        --file portfolio-app/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  legacy-build:
    name: Legacy Build with Java 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-legacy-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-legacy-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup x86 target platform
      uses: canastro/copy-file-action@master
      with:
        source: "portfolio-app/releng/x86/x86-target-definition.target"
        target: "portfolio-target-definition/portfolio-target-definition.target"
    - name: Build with Maven
      run: |
        mvn -Denforcer.skip=true verify \
        --batch-mode \
        --file portfolio-app/pom.xml \
        -pl :portfolio-target-definition,:name.abuchen.portfolio,:name.abuchen.portfolio.tests -am -amd
