name: Windows Build

on:
  push:
    branches:
      - winInstaller
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  windows-build:
    name: Windows Build with Installer
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    - name: Cache Maven repository
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-mvn-
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: zulu
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11
    
    - name: Install NSIS
      run: choco install nsis -y
      shell: powershell
    
    - name: Install jsign
      run: choco install jsign -y
      shell: powershell
    
    - name: Build with Maven
      run: |
        mvn clean verify  --batch-mode --file portfolio-app/pom.xml -Ppackage-distro "-Dinstaller.skip=false" "-Dexesigner.skip=false" 
      shell: powershell
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: windows-build-artifacts
        path: |
          portfolio-product/target/products/*.zip
          portfolio-product/target/products/*.exe
        retention-days: 7
